### ISSUE TITLE
Presentation plan

### ISSUE THREAD

**Issue by roman-koshchei** [flurium/spentoday#61]
План для презентации, как минимум для разработчиков.

**Comment by vitalii-lytvynenko** [comment]
## Технології та Архітектура Веб-сервіса проекту Spentoday	
У розробці проекту Spentoday були використані передові технології та практики для створення високоефективного веб-сервісу для розгортання та запуску інтернет-магазинів. Давайте розглянемо деякі з них.
1. **Мови програмування та фреймворки:**
    - **C#:** Для розробки бекенду використовується C# - потужна та надійна мова програмування від Microsoft.

    - **ASP.NET Core:** Основний фреймворк для створення веб-додатків та API. Він забезпечує високу продуктивність і безпеку.

    - **TypeScript з Svelte і SvelteKit:** Для фронтенду використовуються TypeScript та Svelte/SvelteKit - технології, які дозволяють створювати швидкі та інтерактивні користувацькі інтерфейси.

2. **База даних:**
    - **PostgreSQL:** Використовується PostgreSQL для зберігання даних інтернет-магазинів. Ця система керування базами даних надійна, швидка та масштабована.

3. **Архітектура:**
    - **Многорівнева монолітна архітектура:** Сервіс Spentoday побудований на основі многорівневої монолітної архітектури, що дозволяє логічно розділити функціонал проекту на різні рівні та модулі, забезпечуючи високий рівень організації коду та підтримки.

    - **Системи розгортання:** Для розгортання використовуються платформи **Fly.io** та **Vercel**, що дозволяють автоматизовано розгортати та керувати сервісами в хмарному середовищі.

4. **Розсилка інформації:**
    - Для розсилки електронних листів використовуються сервіси **Resend** та **SendGrid**, що допомагають надійно та ефективно спілкуватися з користувачами.
  
Ці технології та архітектурні підходи дозволили нам створити надійний та швидкий веб-сервіс Spentoday для розгортання інтернет-магазинів, надаючи користувачам можливість легко розпочати свій онлайн-бізнес.
